services:
  - type: web
    name: hinova-uppchannel-monitor
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: HINOVA_TOKEN
        sync: false
      - key: HINOVA_USUARIO
        sync: false
      - key: HINOVA_SENHA
        sync: false
      - key: UPPCHANNEL_API_KEY
        sync: false
      - key: SITUACOES_ATIVAS
        value: "6,15,11,23,38,80,82,30,40,5,10,3,45,77,76,33,8,29,70,71,72,79,32,59,4,20,61"
      - key: INTERVALO_MINUTOS
        value: "15"
